const symptoms = [
    "Fever",
    "Cough",
    "Sore Throat",
    "Body Ache",
    "Chest Pain",
    "Chest Tightness",
    "Shortness of Breath",
    "Wheezing",
    "Dizziness",
    "Confusion",
    "Seizure",
    "Loss of Consciousness",
    "Slurred Speech",
    "Facial Drooping",
    "Limb Weakness",
    "Severe Headache",
    "Abdominal Pain",
    "Nausea",
    "Vomiting",
    "Diarrhea",
    "Blood in Stool",
    "Blood in Urine",
    "Severe Bleeding",
    "Rash",
    "Swollen Tongue",
    "Swollen Throat",
    "Burns",
    "Fracture",
    "Pregnancy Bleeding",
    "Suicidal Thoughts"
];